name:                SomeNews
version:             0.1.0.0
github:              "githubuser/EchoBot"
license:             BSD3
author:              "Evgeny Osipenko"
maintainer:          "delfigamer@yandex.ru"
copyright:           "2020 Evgeny Osipenko"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/SomeNews#readme>

default-extensions: DataKinds, GADTs, OverloadedStrings, RankNTypes, TypeOperators

dependencies:
- QuickCheck
- aeson
- ansi-terminal
- base
- bytestring
- cryptonite
- hspec
- postgresql-simple
- random
- sqlite-simple
- text
- time
- unordered-containers
- warp
- yaml

library:
  source-dirs: src

executables:
  SomeNews-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - SomeNews

tests:
  SomeNews-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - SomeNews
