# - database:
    # sqlite: "temp.sqlite~"
  # sample-size: 100

# - database:
    # sqlite: ""
  # sample-size: 1000

- database:
    postgres:
      user: me
      password: me
  sample-size: 100000
